# Tensorflow v1.0.0 for GPU
FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu16.04
MAINTAINER Edgar Y. Walker <edgar.walker@gmail.com>

# Install essential Ubuntu packages and update pip
RUN apt-get update &&\
    apt-get install -y build-essential \
                       vim \
                       curl \
                       wget \
                       pkg-config \
                       libfreetype6-dev \
                       libssl-dev \
                       libreadline-dev \
                       libzmq3-dev \
                       libpng12-dev \
                       rsync \
                       unzip \
                       gfortran \
                       libblas-dev \
                       liblapack-dev \
                       python3-dev \
                       python3-pip \
                       python3-tk &&\
    ln -s /usr/bin/python3 /usr/local/bin/python &&\
    ln -s /usr/bin/pip3 /usr/local/bin/pip &&\
    pip install --upgrade pip &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install essential Python packages
RUN pip --no-cache-dir install \
         numpy \
         matplotlib \
         scipy \
         pandas \
         jupyter \
         ipykernel \
         tensorflow-gpu &&\
    python -m ipykernel.kernelspec
